language: java
jdk:
- oraclejdk8
env:
  global:
    - TERM=dumb
    - secure: "G3QS3UXodyA9fs7JUCwokRwPuz2vQvk99QSVXmq9I59nTgele2wJ5zwFS8X1TSDisALgderwmv1T/mPDysGOlZHrS/x5n6lx6gQw88TxfZywuhVb5kpcsWzIow+n1yvTaY5YkSGiG/DuABoAlxZQBfxG+GtJNkA0/QZ+6jagyYc="
    - secure: "mM/mXkgI4HPZTJJ/j/cx40RQiykWi9Vj7Pn+zxakkLOvWYMADFLGwSKTKIDMg4R6cVxnkx2De7outBKe9Js1BRRLQ65rVCR4y39ajLobu3FfSlTEy1NkwqEMFETQ3069VD5sAnN1Zs2oRKyX+avXW7o2t/tyfdTyPpikDZ//ixk="
install: 
  - "./gradlew clean test build publish publishBintray"
